services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: censo_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - censo_net
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: censo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: censo
    ports:
      - "3306:3306"
    volumes:
      - ./database/migrations/exemplo_base.sql:/docker-entrypoint-initdb.d/init_bases.sql
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - censo_net

networks:
  censo_net:
    driver: bridge

volumes:
  mysql_data: